// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VieEventAssociation.Infrastructure.SqliteDmPersistence;

#nullable disable

namespace VieEventAssociation.Infrastructure.SqliteDmPersistence.Migrations
{
    [DbContext(typeof(SqliteDmContext))]
    [Migration("20251113160222_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ViaEventManagementSystem.Core.Domain.Aggregates.Events.Entities.Invitation.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("_EventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("EventId");

                    b.Property<Guid>("_GuestId")
                        .HasColumnType("TEXT")
                        .HasColumnName("GuestId");

                    b.Property<string>("_InvitationStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("_EventId");

                    b.HasIndex("_GuestId");

                    b.ToTable("Invitations", (string)null);
                });

            modelBuilder.Entity("ViaEventManagementSystem.Core.Domain.Aggregates.Events.ViaEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("_Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("_EndDateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("EndDateTime");

                    b.Property<string>("_EventStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Status");

                    b.Property<string>("_EventTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.Property<string>("_EventVisibility")
                        .HasColumnType("TEXT")
                        .HasColumnName("Visibility");

                    b.Property<int?>("_MaxNumberOfGuests")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaxNumberOfGuests");

                    b.Property<DateTime?>("_StartDateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("StartDateTime");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ViaEventManagementSystem.Core.Domain.Aggregates.Guests.ViaGuest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("_Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("_FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FirstName");

                    b.Property<string>("_LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LastName");

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("ViaEventManagementSystem.Core.Domain.Aggregates.Events.Entities.Invitation.Invitation", b =>
                {
                    b.HasOne("ViaEventManagementSystem.Core.Domain.Aggregates.Events.ViaEvent", null)
                        .WithMany("_Invitations")
                        .HasForeignKey("_EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViaEventManagementSystem.Core.Domain.Aggregates.Guests.ViaGuest", null)
                        .WithMany()
                        .HasForeignKey("_GuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ViaEventManagementSystem.Core.Domain.Aggregates.Events.ViaEvent", b =>
                {
                    b.OwnsMany("ViaEventManagementSystem.Core.Domain.Aggregates.Guests.ValueObjects.GuestId", "_GuestsParticipants", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT")
                                .HasColumnName("GuestId");

                            b1.HasKey("EventId", "Value");

                            b1.ToTable("EventGuestParticipation", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.Navigation("_GuestsParticipants");
                });

            modelBuilder.Entity("ViaEventManagementSystem.Core.Domain.Aggregates.Events.ViaEvent", b =>
                {
                    b.Navigation("_Invitations");
                });
#pragma warning restore 612, 618
        }
    }
}
